### ISSUE TITLE
What is the specific effect of `build_threads`?

### ISSUE THREAD

**Issue by jrr** [react-native-community/react-native-circleci-orb#19]
# Question

I can see that the `build_threads` parameter sets `BUILD_THREADS` in the environment of the linux_android [executor](https://github.com/react-native-community/react-native-circleci-orb/blob/master/src/executors/linux_android.yml), which specifies the [reactnativecommunity/react-native-android](https://hub.docker.com/r/reactnativecommunity/react-native-android/) Docker image, but that's where I lose the trail.

What tool(s) are affected by this env var? Gradle? Metro?

**Comment by matt-oakes** [comment]
I added it because it was in this file of React Native core:

https://github.com/facebook/react-native/blob/db4a7ae9b8245c60e6d820dc2d1b22d469867a51/.circleci/config.yml#L33

To be honest though I can't actually see any reference online to what it does. I will likely remove it as it seems to be useless now.
