### ISSUE TITLE
Update default version to node 10 or 12?

### ISSUE THREAD

**Issue by Naturalclar** [react-native-community/react-native-circleci-orb#31]
## What would you like to be added

Currently, the default value of node version is 8.
I'd like to suggest to upgrade the default version to 10 or 12.

## Why is this needed

Node version 8 has reached its EOL in 2020.

https://nodejs.org/en/about/releases/

**Comment by roni-castro** [comment]
Thanks for the information @Naturalclar. Currently on the project we have node version 8 being declared in three different places. I will try to update them soon in my testing Orb project of this repo and check if it will be a breaking change.

Here are the places we use specific version of node (Highlighted in yellow):

https://github.com/react-native-community/react-native-circleci-orb/blame/83e9c2ed3b5cf0c15422f5b701cef4dc315d926f/.circleci/config.yml#L24

https://github.com/react-native-community/react-native-circleci-orb/blame/7c5b51a6c2752ed9f0975a24b5bd86764f178d72/src/commands/setup_macos_executor.yml#L24

https://github.com/react-native-community/react-native-circleci-orb/blame/9dff062b55dd60327825ea04429a383d8b37cace/src/executors/linux_js.yml#L5

**Comment by safaiyeh** [comment]
Thanks for the issue @Naturalclar.

Yeah I just upgraded to v8.0.0 of @semantic-release/git and they dropped Node v8 support. Came here to create and issue as well. Thanks for looking into it @roni-castro

**Comment by matt-oakes** [comment]
Thanks for looking into this @roni-castro. Feel free to open a PR with the changes when you're ready.

**Comment by roni-castro** [comment]
I have made the updates and it worked on one of my projects, but  I still need to run the macos build and tests on another project, soon I will open a PR.

**Comment by safaiyeh** [comment]
Latest as in `v13.6.0`?

I would like an option latest LTS version.

**Comment by Naturalclar** [comment]
Thanks for working on this!

I'd also prefer `lts` over `latest` being the default

**Comment by lfalkner** [comment]
Several libraries in RN do not support node 12 yet, it may be wiser to approach with 10 as a default, and document usage for overriding the node_version for the rn/linux_js executor.

For example, i've tried using the latest of this orb, and this configuration fails `circleci config validate`

```
executors:
  rn/linux_js:
    node_version: "10.16.0"
```

**Comment by roni-castro** [comment]
Brew does not have [`lts` version](https://github.com/Homebrew/brew/issues/6317). I have tried using version 12, but for some reason this version generated an error on CI, when trying to install it with brew (image below), even though `brew install node@12`  works on my local machine and exists  according to the [docs](https://formulae.brew.sh/formula/node).

So I will update it to version 10 which worked in all my projects. If someone is interested in testing on your project this is the Orb: [roni-castro/react-native-circleci-orb@2.1.1](https://circleci.com/orbs/registry/orb/react-native-circleci-orb/react-native-circleci-orb), which I will open a PR soon.

**Comment by lfalkner** [comment]
@roni-castro I'm seeing the same issue with your branch as with the latest release, I'm getting a corrupted tarball from yarn / npm. The "best" solution we've come across, and what I've seen suggested is to pass the network concurrency flag to yarn install. Otherwise, any packages that have `prepare` included in their package.json will trigger a build within the yarn install command, which . can corrupt the cache, so it leads to intermittent build failures. 
`yarn install --network-concurrency 1`

**Comment by roni-castro** [comment]
> @roni-castro I'm seeing the same issue with your forked orb as with the latest release, I'm getting a corrupted tarball from yarn / npm. The "best" solution we've come across, and what I've seen suggested is to pass the network concurrency flag to yarn install. Otherwise, any packages that have `prepare` included in their package.json will trigger a build within the yarn install command, which . can corrupt the cache, so it leads to intermittent build failures.
> `yarn install --network-concurrency 1`
> [related issue with yarn](https://github.com/yarnpkg/yarn/issues/6312)

Hi @lfalkner, thanks for the information. I think this problem is not related with the node update, as the latest version of this repo uses node 8. 
Please, open another issue with more details, the error message and your suggestion, and if possible, please try downgrading the version to `1.5.0` and/or `1.4.0` of this repo to see if this problem also occurs.

**Comment by lfalkner** [comment]
Hi @roni-castro thank you, I apologize for the confusion. This problem is not related to the node update, but it does block me from using the containers, unfortunately. Because we have some modules which require yarn to run a `prepare` step, we cannot use `yarn install` as-is on your containers. :( If I have time later on this week, I can try exposing the parameters to the `yarn install` command you've written as environment variables, and try testing again. Thanks!
