### ISSUE TITLE
Run android_test in linux_android instead of macos

### ISSUE THREAD

**Issue by Masadow** [react-native-community/react-native-circleci-orb#57]
## What would you like to be added

I would prefer not to rely on macos if testing for Android.

## Why is this needed

I currently want to test only Android on CircleCI and therefore does not have a plan to run macos machines. I should be able to use the orb for android without macos machines

On a side note, I'm not sure if it was intended to run android_test in macos while android_build run on android_linux

**Comment by matt-oakes** [comment]
👋 This was a deliberate decision because CircleCI used to really struggle to run the Android emulator on a linux runner. I believe this was because Linux is running in a Docker environment, which uses virtualisation, and the Android emulator also uses virtualisation. This nested virtualization caused a lot of problems with the Android emulator.

The options were to either rely on something like Firebase Test Lab or AWS Device Farm, or to run the Android tests on macOS. The latter was chosen.

The reason for doing the Android building on Linux is to minimise the amount of time spent running in the macOS environment, which is much more expensive on CircleCI. As the artefacts needed are just the APKs, it doesn't matter what environment creates them.
