### ISSUE TITLE
`rn/android_test` fails with brew error

### ISSUE THREAD

**Issue by TrebuhD** [react-native-community/react-native-circleci-orb#95]
### What happened

My config.yml:
```
      - rn/android_test:
          detox_configuration: android.emu.release
          requires:
            - install
            - build-android-artifact-prod
```

This step results in the following error:
```
Error: Invalid cask: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/emacs.rb
Cask ''/Applications/Emacs.app/Contents/Resources/man/man1/ebrowse.1.gz' is not a valid man page name' definition is invalid.
Error: Cannot tap homebrew/cask: invalid syntax in tap!
```

AFAIK, this can be fixed by running `brew update` before executing the `rn_android_test` job, but the orb has `HOMEBREW_NO_AUTO_UPDATE=1` hardcoded so that's probably the reason it's failing.

**Comment by kieran-osgood** [comment]
Also noticed this happens on the `ios_build_and_test` job, specifically it was completing successfully when I was using `project_path: "ios/projectNamexcodeproj"` but started failing after using the `project_path: "ios/projectName.xcodeworkspace"` (which was a change I'd made due to ios builds failing using the proj)

**Comment by lukebrandonfarrell** [comment]
Upgrading to latest fixed it for me

**Comment by vonovak** [comment]
this is fixed in latest, closing :)
